version: '3.8'

services:
  web:
    image: php:8.2-fpm
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db

    command: >
      sh -c "docker-php-ext-install mysqli && php-fpm"

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: poseidon
      MYSQL_DATABASE: DP-PRJ
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql #ajoute la base de données init.sql sinon il ne la voit pas

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./web:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_data:
